### ISSUE TITLE
User Model question

### ISSUE THREAD

**Issue by JanStevens** [jagthedrummer/so_auth#3]
Hello,

Why should I create a user model (db table) for the so_auth client? Isn't the idea to have a centralised user management system?

In the so_provide example you create devise users.

Thanks!

**Comment by jagthedrummer** [comment]
Hey @JanStevens, the idea is indeed to have centralized user management.  In your "leaf apps" (the ones using so_auth client) you'll still want to have some sort of representation of you users so that you can allow users to "own" things.  It's mostly to allow you to do db joins and what not.  For instance if your client app was a blogging app, you'd want to be able to track which users have created which posts.  So you need an "internal" (to the leaf app) representation of the user.  All of the user info will be passed to the leaf app from the central user app (so_auth_provider) during the OAuth dance.  So users will update and maintain their "profile" in the provider app, but then those details are made available to the client apps.  Does that make sense?

**Comment by JanStevens** [comment]
Yes it totally makes sense but for me defeats the purpose of using SSO.

My idea was always to use oauth for SSO and a centralised user system where my leaf apps don't need to know anything about my users. After 20 or more smaller leaf apps (services), I will have a lot of duplicated data.

Does your implementation follow the oauth spec or is it an adaptation to fit your personal/business needs?

Thanks for your reply

**Comment by jagthedrummer** [comment]
The OAuth spec says that the provider should pass user info back to the client apps.  It does not specify what the client app should do with it.  So, what you do with it from there is up to you.  In practice I've never found the "duplicated data" to be an issue at all.  The benefits of having many small apps instead of one giant monolith easily outweigh the tiny overhead of storing a small amount of redundant user data.  What sort of problems are you envisioning?

**Comment by JanStevens** [comment]
So basically any information I send from the provider to the leaf apps can then be used in the leaf apps.

This also means that password resets/changing user info/managing users (as admin of some sort) should be handled by the provider, any updates will then be send to the leaf nodes (if the user accesses the app).

Thanks for your explanation, it seems that my initial idea of SSO/CAS was wrong.

Regards

**Comment by jagthedrummer** [comment]
No problem, I'm happy to help.  Let me know if you come across any other questions.

**Comment by JanStevens** [comment]
Hello

I'm trying to use your gem for multiple domain applications. I notice that the cookie_valid? will use the provider app's cookie to check if the user is valid. Now I'm wondering how I can do this with different domains. In my client app I dont have access to the providers cookie.

I noticed that using different domains and altering the cookie_valid? check to only look for a session[:user_id] works (we still have SSO) but the global logout does not work (quite logic, since we cannot remove the others app cookie and the other apps session only checks if there is a session[:user_id]).

Now the question, how can I make this work with multiple domains? Should I selectively share the cookie from the provider with my client apps or should I handle the global logout in a different way?

Thanks a lot for your time!

**Comment by jagthedrummer** [comment]
Honestly, I'm not sure what you'd want to do with multiple domains.  You could potentially just have a short session time out in your client app, so that the OAuth dance is happening more often.  If the provider is a site you don't control (like GitHub or Twitter) you could check their OAuth docs to see if they have any recommendations.  Sorry I don't have anything better for you.
